"""init schema

Revision ID: c68fe1bdc9df
Revises: 
Create Date: 2025-12-16 18:24:01.430452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c68fe1bdc9df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_code'), 'building', ['code'], unique=True)
    op.create_index(op.f('ix_building_id'), 'building', ['id'], unique=False)
    op.create_table('guest',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ba_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rk', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dt_of_req', sa.Date(), nullable=True),
    sa.Column('id_card_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pers_mobile_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accompanying_num', sa.Integer(), nullable=False),
    sa.Column('spouse', sa.Boolean(), nullable=False),
    sa.Column('children', sa.Boolean(), nullable=False),
    sa.Column('car', sa.Boolean(), nullable=False),
    sa.Column('car_num', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('batman', sa.Boolean(), nullable=False),
    sa.Column('names_accompanying', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('purpose_of_use', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alot_room', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('res_1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('res_2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('res_3', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('res_4', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_type',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('base_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_type_id'), 'room_type', ['id'], unique=False)
    op.create_index(op.f('ix_room_type_name'), 'room_type', ['name'], unique=False)
    op.create_table('user_account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=True)
    op.create_index(op.f('ix_user_account_id'), 'user_account', ['id'], unique=False)
    op.create_index(op.f('ix_user_account_role'), 'user_account', ['role'], unique=False)
    op.create_table('guest_photo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('object_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('captured_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['captured_by_user_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_photo_guest_id'), 'guest_photo', ['guest_id'], unique=False)
    op.create_index(op.f('ix_guest_photo_id'), 'guest_photo', ['id'], unique=False)
    op.create_table('reservation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_guest_id'), 'reservation', ['guest_id'], unique=False)
    op.create_index(op.f('ix_reservation_id'), 'reservation', ['id'], unique=False)
    op.create_index(op.f('ix_reservation_status'), 'reservation', ['status'], unique=False)
    op.create_table('room',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('room_type_id', sa.Uuid(), nullable=False),
    sa.Column('room_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_building_id'), 'room', ['building_id'], unique=False)
    op.create_index(op.f('ix_room_id'), 'room', ['id'], unique=False)
    op.create_index(op.f('ix_room_room_number'), 'room', ['room_number'], unique=False)
    op.create_index(op.f('ix_room_room_type_id'), 'room', ['room_type_id'], unique=False)
    op.create_index(op.f('ix_room_status'), 'room', ['status'], unique=False)
    op.create_table('folio',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folio_id'), 'folio', ['id'], unique=False)
    op.create_index(op.f('ix_folio_reservation_id'), 'folio', ['reservation_id'], unique=True)
    op.create_table('reservation_room',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reservation_id', sa.Uuid(), nullable=False),
    sa.Column('room_type_id', sa.Uuid(), nullable=True),
    sa.Column('room_id', sa.Uuid(), nullable=True),
    sa.Column('occupants', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_room_id'), 'reservation_room', ['id'], unique=False)
    op.create_index(op.f('ix_reservation_room_reservation_id'), 'reservation_room', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_reservation_room_room_id'), 'reservation_room', ['room_id'], unique=False)
    op.create_index(op.f('ix_reservation_room_room_type_id'), 'reservation_room', ['room_type_id'], unique=False)
    op.create_index(op.f('ix_reservation_room_status'), 'reservation_room', ['status'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('folio_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('received_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['folio_id'], ['folio.id'], ),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_folio_id'), 'payment', ['folio_id'], unique=False)
    op.create_index(op.f('ix_payment_id'), 'payment', ['id'], unique=False)
    op.create_index(op.f('ix_payment_received_by_user_id'), 'payment', ['received_by_user_id'], unique=False)
    op.create_table('stay',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reservation_room_id', sa.Uuid(), nullable=False),
    sa.Column('check_in_at', sa.DateTime(), nullable=True),
    sa.Column('check_out_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_room_id'], ['reservation_room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stay_id'), 'stay', ['id'], unique=False)
    op.create_index(op.f('ix_stay_reservation_room_id'), 'stay', ['reservation_room_id'], unique=True)
    op.create_index(op.f('ix_stay_status'), 'stay', ['status'], unique=False)
    op.create_table('folio_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('folio_id', sa.Uuid(), nullable=False),
    sa.Column('stay_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['folio_id'], ['folio.id'], ),
    sa.ForeignKeyConstraint(['stay_id'], ['stay.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folio_item_folio_id'), 'folio_item', ['folio_id'], unique=False)
    op.create_index(op.f('ix_folio_item_id'), 'folio_item', ['id'], unique=False)
    op.create_index(op.f('ix_folio_item_stay_id'), 'folio_item', ['stay_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_folio_item_stay_id'), table_name='folio_item')
    op.drop_index(op.f('ix_folio_item_id'), table_name='folio_item')
    op.drop_index(op.f('ix_folio_item_folio_id'), table_name='folio_item')
    op.drop_table('folio_item')
    op.drop_index(op.f('ix_stay_status'), table_name='stay')
    op.drop_index(op.f('ix_stay_reservation_room_id'), table_name='stay')
    op.drop_index(op.f('ix_stay_id'), table_name='stay')
    op.drop_table('stay')
    op.drop_index(op.f('ix_payment_received_by_user_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_folio_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_reservation_room_status'), table_name='reservation_room')
    op.drop_index(op.f('ix_reservation_room_room_type_id'), table_name='reservation_room')
    op.drop_index(op.f('ix_reservation_room_room_id'), table_name='reservation_room')
    op.drop_index(op.f('ix_reservation_room_reservation_id'), table_name='reservation_room')
    op.drop_index(op.f('ix_reservation_room_id'), table_name='reservation_room')
    op.drop_table('reservation_room')
    op.drop_index(op.f('ix_folio_reservation_id'), table_name='folio')
    op.drop_index(op.f('ix_folio_id'), table_name='folio')
    op.drop_table('folio')
    op.drop_index(op.f('ix_room_status'), table_name='room')
    op.drop_index(op.f('ix_room_room_type_id'), table_name='room')
    op.drop_index(op.f('ix_room_room_number'), table_name='room')
    op.drop_index(op.f('ix_room_id'), table_name='room')
    op.drop_index(op.f('ix_room_building_id'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_reservation_status'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_id'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_guest_id'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_guest_photo_id'), table_name='guest_photo')
    op.drop_index(op.f('ix_guest_photo_guest_id'), table_name='guest_photo')
    op.drop_table('guest_photo')
    op.drop_index(op.f('ix_user_account_role'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_id'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_index(op.f('ix_room_type_name'), table_name='room_type')
    op.drop_index(op.f('ix_room_type_id'), table_name='room_type')
    op.drop_table('room_type')
    op.drop_table('guest')
    op.drop_index(op.f('ix_building_id'), table_name='building')
    op.drop_index(op.f('ix_building_code'), table_name='building')
    op.drop_table('building')
    # ### end Alembic commands ###
